import { ChangeEvent, FormEvent, useEffect, useState } from 'react'
import { Copy, DatabaseBackup, Download, KeyRound, Save, ShieldCheck, Upload } from 'lucide-react'
import { api } from '../api'
import type { BusinessSettings, Profile, TwoFactorSetup } from '../types'
import { ErrorMessage, Loading, PageHeader, SuccessMessage } from '../ui'

export function SettingsPage({ profile, isAdmin, onProfileChange }: { profile: Profile; isAdmin: boolean; onProfileChange: (profile: Profile) => void }) {
  const [settings, setSettings] = useState<BusinessSettings>()
  const [tab, setTab] = useState<'general' | 'security' | 'backup'>('general')
  const [setup, setSetup] = useState<TwoFactorSetup>(); const [code, setCode] = useState(''); const [recoveryCodes, setRecoveryCodes] = useState<string[]>([])
  const [backupFile, setBackupFile] = useState<unknown>(); const [confirmation, setConfirmation] = useState('')
  const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { api.settings().then(setSettings).catch(reason => setError((reason as Error).message)) }, [])

  async function save(event: FormEvent) { event.preventDefault(); if (!settings) return; setBusy(true); setError(''); try { setSettings(await api.saveSettings(settings)); setSuccess('Configuración guardada.') } catch (reason) { setError((reason as Error).message) } finally { setBusy(false) } }
  async function beginTwoFactor() { setBusy(true); setError(''); try { setSetup(await api.setupTwoFactor()); setRecoveryCodes([]) } catch (reason) { setError((reason as Error).message) } finally { setBusy(false) } }
  async function enableTwoFactor() { setBusy(true); setError(''); try { const result = await api.enableTwoFactor(code); setRecoveryCodes(result.recoveryCodes); setSetup(undefined); setCode(''); onProfileChange(await api.me()); setSuccess('Autenticación de dos pasos activada. Guarda los códigos de recuperación.') } catch (reason) { setError((reason as Error).message) } finally { setBusy(false) } }
  async function disableTwoFactor() { if (!window.confirm('¿Desactivar la autenticación de dos pasos?')) return; setBusy(true); setError(''); try { await api.disableTwoFactor(); onProfileChange(await api.me()); setSetup(undefined); setRecoveryCodes([]); setSuccess('Autenticación de dos pasos desactivada.') } catch (reason) { setError((reason as Error).message) } finally { setBusy(false) } }
  async function readBackup(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; try { setBackupFile(JSON.parse(await file.text())); setSuccess(`Archivo ${file.name} listo para restaurar.`); setError('') } catch { setBackupFile(undefined); setError('El archivo seleccionado no es un JSON válido.') } }
  async function restore() { if (!backupFile || confirmation !== 'RESTAURAR') { setError('Selecciona un respaldo y escribe RESTAURAR para confirmar.'); return } if (!window.confirm('Esta acción reemplazará catálogos, ajustes, cotizaciones y ventas. Las cuentas de usuario se conservarán. ¿Continuar?')) return; setBusy(true); setError(''); try { const result = await api.restoreBackup(backupFile, confirmation); setSuccess(`${result.message} Cotizaciones recuperadas: ${result.quotes}.`); setBackupFile(undefined); setConfirmation(''); setSettings(await api.settings()) } catch (reason) { setError((reason as Error).message) } finally { setBusy(false) } }

  return <>
    <PageHeader eyebrow="SISTEMA" title="Configuración" description="Datos del negocio, fórmula de costos, protección de cuenta y respaldos." />
    <div className="tabs"><button className={tab === 'general' ? 'active' : ''} onClick={() => setTab('general')}>Negocio y costos</button><button className={tab === 'security' ? 'active' : ''} onClick={() => setTab('security')}>Seguridad</button>{isAdmin && <button className={tab === 'backup' ? 'active' : ''} onClick={() => setTab('backup')}>Respaldos</button>}</div>
    <ErrorMessage error={error} /><SuccessMessage message={success} />
    {tab === 'general' && (!settings ? <Loading /> : <form className="panel settings-form" onSubmit={save}>
      <div className="section-title"><div><p className="eyebrow">IDENTIDAD</p><h2>Datos generales</h2></div></div>
      <div className="form-grid three"><label>Nombre del negocio<input disabled={!isAdmin} value={settings.businessName} onChange={e => setSettings({ ...settings, businessName: e.target.value })} /></label><label>Nombre de moneda<input disabled={!isAdmin} value={settings.currencyName} onChange={e => setSettings({ ...settings, currencyName: e.target.value })} /></label><label>Símbolo<input disabled={!isAdmin} value={settings.currencySymbol} onChange={e => setSettings({ ...settings, currencySymbol: e.target.value })} /></label></div>
      <hr /><div className="section-title"><div><p className="eyebrow">FÓRMULA ORIGINAL</p><h2>Costos y precio</h2></div></div>
      <div className="form-grid three"><label>Electricidad por kWh<input disabled={!isAdmin} type="number" min="0" step="0.01" value={settings.electricityPerKwh} onChange={e => setSettings({ ...settings, electricityPerKwh: Number(e.target.value) })} /></label><label>Mantenimiento por impresión<input disabled={!isAdmin} type="number" min="0" step="0.01" value={settings.maintenancePerPrint} onChange={e => setSettings({ ...settings, maintenancePerPrint: Number(e.target.value) })} /></label><label>Multiplicador predeterminado<input disabled={!isAdmin} type="number" min="1" step="0.01" value={settings.defaultProfitMultiplier} onChange={e => setSettings({ ...settings, defaultProfitMultiplier: Number(e.target.value) })} /></label><label>Impuesto (%)<input disabled={!isAdmin} type="number" min="0" step="0.01" value={settings.taxPercent} onChange={e => setSettings({ ...settings, taxPercent: Number(e.target.value) })} /></label><label>Redondear a<input disabled={!isAdmin} type="number" min="0" step="0.01" value={settings.roundTo} onChange={e => setSettings({ ...settings, roundTo: Number(e.target.value) })} /></label><label>Decimales<input disabled={!isAdmin} type="number" min="0" max="4" step="1" value={settings.decimalPlaces} onChange={e => setSettings({ ...settings, decimalPlaces: Number(e.target.value) })} /></label></div>
      <div className="formula-note"><strong>Cómo se calcula</strong><span>Consumibles + electricidad + mantenimiento + materiales adicionales → ganancia → impuesto → redondeo.</span></div>
      {isAdmin ? <div className="editor-actions"><button disabled={busy}><Save size={17} />Guardar configuración</button></div> : <p className="muted">Solo un administrador puede modificar estos valores.</p>}
    </form>)}
    {tab === 'security' && <section className="panel security-panel"><div className="security-hero"><div className="security-icon"><ShieldCheck size={28} /></div><div><p className="eyebrow">TU CUENTA</p><h2>Autenticación de dos pasos</h2><p>Además de tu contraseña, solicita un código temporal generado en una aplicación como Google Authenticator, Microsoft Authenticator o 2FAS.</p></div><span className={`status ${profile.twoFactorEnabled ? 'ok' : 'warning'}`}>{profile.twoFactorEnabled ? 'ACTIVADA' : 'DESACTIVADA'}</span></div>
      {!profile.twoFactorEnabled && !setup && <button disabled={busy} onClick={beginTwoFactor}><KeyRound size={17} />Configurar 2FA</button>}
      {setup && <div className="setup-box"><h3>1. Agrega la cuenta en tu autenticador</h3><p>Copia esta clave manual o abre el enlace desde un dispositivo compatible.</p><div className="secret"><code>{setup.sharedKey}</code><button className="icon ghost" onClick={() => navigator.clipboard.writeText(setup.sharedKey)} title="Copiar"><Copy size={16} /></button></div><a className="text-link" href={setup.authenticatorUri}>Abrir en aplicación de autenticación</a><h3>2. Confirma el código de seis dígitos</h3><div className="inline-form"><label>Código<input inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e => setCode(e.target.value)} /></label><button disabled={busy || code.trim().length < 6} onClick={enableTwoFactor}>Activar</button></div></div>}
      {profile.twoFactorEnabled && <button className="ghost danger-text" disabled={busy} onClick={disableTwoFactor}>Desactivar autenticación de dos pasos</button>}
      {recoveryCodes.length > 0 && <div className="recovery-box"><h3>Códigos de recuperación</h3><p>Cada código funciona una sola vez. Guárdalos en un lugar privado; no volverán a mostrarse.</p><div className="recovery-grid">{recoveryCodes.map(value => <code key={value}>{value}</code>)}</div><button className="ghost" onClick={() => navigator.clipboard.writeText(recoveryCodes.join('\n'))}><Copy size={16} />Copiar códigos</button></div>}
    </section>}
    {tab === 'backup' && isAdmin && <div className="backup-grid"><section className="panel backup-card"><div className="security-icon"><DatabaseBackup size={25} /></div><h2>Crear respaldo</h2><p>Descarga catálogos, configuración, cotizaciones y ventas en JSON. Las contraseñas y claves 2FA nunca se incluyen.</p><button onClick={() => api.exportBackup().catch(reason => setError((reason as Error).message))}><Download size={17} />Descargar respaldo</button></section><section className="panel backup-card danger-zone"><div className="security-icon"><Upload size={25} /></div><h2>Restaurar respaldo</h2><p>Reemplaza los datos operativos actuales. Las cuentas de acceso se mantienen intactas.</p><label className="file-picker">Archivo JSON<input type="file" accept="application/json,.json" onChange={readBackup} /></label><label>Confirmación<input value={confirmation} onChange={e => setConfirmation(e.target.value)} placeholder="Escribe RESTAURAR" /></label><button className="danger-button" disabled={busy || !backupFile || confirmation !== 'RESTAURAR'} onClick={restore}><Upload size={17} />Restaurar datos</button></section></div>}
  </>
}
